# Standards: 0.1
---
- name: Fact python user
  set_fact:
    python_user: "{{ python_user | default(homebrew_user) | default(ansible_user_id) }}"
  tags:
    - python

- name: Install required package
  when: python_install
  ignore_errors: True
  homebrew_cask:
    name: python
    state: latest
  become: "{{ (python_user != ansible_user_id) | bool }}"
  become_user: "{{ python_user }}"
  tags:
    - python

- name: Install user packages
  loop: "{{ python_user_packages }}"
  loop_control:
    label: "{{ item.name | default(item) }}"
  gem:
    executable: "{{ item.executable | default(python_pip_executable) | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    extra_args: --user
    state: "{{ item.state | default('latest') }}"
  become: "{{ (python_user != ansible_user_id) | bool }}"
  become_user: "{{ python_user }}"
  tags:
    - python

- name: Install global packages
  loop: "{{ python_global_packages }}"
  loop_control:
    label: "{{ item.name | default(item) }}"
  gem:
    executable: "{{ item.executable | default(python_pip_executable) | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('latest') }}"
  tags:
    - python

...
